---
title: "AMC Subintern 2016 report"
author: "AMC Subintern"
date: "2016년 8월 11일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(knitr)
library(dplyr)
setwd("D:/Subintern/WNL")
```

## 2016 Summer

- 서브인턴 어지안, 이종희 선생님
- 한성필 작성

```{r}
PKRaw = read.csv("Drug_X_PK.csv")

DosePK = PKRaw %>% 
  group_by(ID) %>% 
  mutate(RankDV = min_rank(desc(DV))) %>% 
  filter(RankDV == 1) %>% 
  select(ID, Tmax = TIME, Cmax = DV, GENE, Drug) %>% 
  group_by(Drug) %>% 
  summarise(Tmax.Mean = mean(Tmax), Cmax.Mean = mean(Cmax))
# -> this result will be used to draw plot.

kable(DosePK)
```

위 표는 Dose에 따른 T~max~와 C^max^를 정리한 것입니다.

$$
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0
\end{vmatrix}  
$$


## 그림 그리기
지금부터는 위에서 작업한 자료를 이용하여 그림을 그려보겠습니다.
```{r}
library(tidyr)

TidyDosePK = gather(DosePK, key = PARAMETER, VALUE, Tmax.Mean:Cmax.Mean)
ggplot(TidyDosePK) +
  geom_point(mapping = aes(x = Drug, y = VALUE, color = PARAMETER)) +
  geom_line(mapping = aes(x = Drug, y = VALUE, color = PARAMETER))


# for fun (PK)
PK = read.csv("Xproject_Final Parameters Pivoted.csv") # WNL
TidyPK = gather(PK, WNLPARAMTER, WNLVALUE, 2:dim(PK)[2])
ggplot(TidyPK) +
  geom_point(mapping = aes(x = ID, y = WNLVALUE, color = WNLPARAMTER)) +
  geom_line(mapping = aes(x = ID, y = WNLVALUE, color = WNLPARAMTER))





# ggplot2 - put all data in a single plot
```
